
<div class="top">
   <ul>
    <li><img src="img/logo-black.svg" alt="" width="40" class="logo"></li>
    <li><span><h2>+7(495) 505-63-94</h2></span></li>
    <li><a href="#"><img src="img/location.svg" alt="" width="20" class="cart"></a></li>
    <li><a href="#"><img src="img/user.svg" alt="" width="20" class="cart"></a></li>
    <li><a href="#"><img src="img/cart.svg" alt="" width="20" class="cart"></a></li>
  </ul>
</div>
